package io.github.kmplitert.core

expect suspend fun loadResourceAsBytes(name: String): ByteArray

expect fun LiteRTAccelerator.isSupportedOnCurrentPlatform(): Boolean

const val CELSIUS_TO_FAHRENHEIT_MODEL_BASE64 =
    "HAAAAFRGTDMUACAAHAAYABQAEAAMAAAACAAEABQAAAAcAAAAHAAAAHQAAABMAQAA" +
    "XAEAABQDAAADAAAAAAAAAAIAAAA0AAAABAAAANz///8GAAAABAAAABMAAABDT05W" +
    "RVJTSU9OX01FVEFEQVRBAAgADAAIAAQACAAAAAUAAAAEAAAAEwAAAG1pbl9ydW50" +
    "aW1lX3ZlcnNpb24ABwAAANQAAADMAAAAuAAAAJwAAACUAAAAdAAAAAQAAABi////" +
    "BAAAAGAAAAAQAAAAAAAAAAgADgAIAAQACAAAABAAAAAkAAAAAAAGAAgABAAGAAAA" +
    "BAAAAAAAAAAMABgAFAAQAAwABAAMAAAAlXasyTA/XcgDAAAAAgAAAAQAAAAGAAAA" +
    "Mi4yMC4wAADO////BAAAABAAAAAxLjUuMAAAAAAAAAAAAAAAHP7//+7///8EAAAA" +
    "BAAAAIhM50EAAAYACAAEAAYAAAAEAAAABAAAAIoi6z9I/v//TP7//w8AAABNTElS" +
    "IENvbnZlcnRlZC4AAQAAABQAAAAAAA4AGAAUABAADAAIAAQADgAAABQAAAAcAAAA" +
    "YAAAAGQAAABoAAAABAAAAG1haW4AAAAAAQAAABQAAAAAAA4AFAAAABAADAALAAQA" +
    "DgAAABAAAAAAAAAIDAAAABAAAADM/v//AQAAAAMAAAADAAAAAAAAAAEAAAACAAAA" +
    "AQAAAAMAAAABAAAAAAAAAAQAAADsAAAAiAAAAEAAAAAEAAAAOv///wAAAAEQAAAA" +
    "EAAAAAQAAAAYAAAAJP///wgAAABJZGVudGl0eQAAAAACAAAAAQAAAAEAAABy////" +
    "AAAAARAAAAAQAAAAAwAAACgAAABc////GAAAAHNlcXVlbnRpYWxfMS9kZW5zZV8x" +
    "L0FkZAAAAAABAAAAAQAAALb///8AAAABEAAAABAAAAACAAAAKAAAAKD///8bAAAA" +
    "c2VxdWVudGlhbF8xL2RlbnNlXzEvTWF0TXVsAAIAAAABAAAAAQAAAAAAFgAYABQA" +
    "AAAQAAwACAAAAAAAAAAHABYAAAAAAAABFAAAABQAAAABAAAAGAAAAAQABAAEAAAA" +
    "BwAAAGlucHV0X2MAAgAAAAEAAAABAAAAAQAAABAAAAAMAAwACwAAAAAABAAMAAAA" +
    "CQAAAAAAAAk="

const val CELSIUS_TO_FAHRENHEIT_EX_MODEL_BASE64 =
    "HAAAAFRGTDMUACAAHAAYABQAEAAMAAAACAAEABQAAAAcAAAAHAAAAHQAAAB0AQAA" +
    "hAEAAEADAAADAAAAAAAAAAIAAAA0AAAABAAAANz///8GAAAABAAAABMAAABDT05W" +
    "RVJTSU9OX01FVEFEQVRBAAgADAAIAAQACAAAAAUAAAAEAAAAEwAAAG1pbl9ydW50" +
    "aW1lX3ZlcnNpb24ABwAAAPwAAAD0AAAAwAAAAJwAAACUAAAAdAAAAAQAAABa////" +
    "BAAAAGAAAAAQAAAAAAAAAAgADgAIAAQACAAAABAAAAAkAAAAAAAGAAgABAAGAAAA" +
    "BAAAAAAAAAAMABgAFAAQAAwABAAMAAAASF8JLEYtHrwDAAAAAgAAAAQAAAAGAAAA" +
    "Mi4yMC4wAADG////BAAAABAAAAAxLjUuMAAAAAAAAAAAAAAA8P3//+b///8EAAAA" +
    "DAAAAAIAAEKMAABCAAAAQgAABgAIAAQABgAAAAQAAAAkAAAAXmbmPyniz7Qo4Do1" +
    "0GVaub9W5j/O4DW5GGNXtkaM2bU0ZuY/RP7//0j+//8PAAAATUxJUiBDb252ZXJ0" +
    "ZWQuAAEAAAAUAAAAAAAOABgAFAAQAAwACAAEAA4AAAAUAAAAHAAAAGAAAABkAAAA" +
    "aAAAAAQAAABtYWluAAAAAAEAAAAUAAAAAAAOABQAAAAQAAwACwAEAA4AAAAQAAAA" +
    "AAAACAwAAAAQAAAAyP7//wEAAAADAAAAAwAAAAAAAAABAAAAAgAAAAEAAAADAAAA" +
    "AQAAAAAAAAAEAAAA8AAAAIwAAABAAAAABAAAADb///8AAAABEAAAABAAAAAEAAAA" +
    "GAAAACD///8IAAAASWRlbnRpdHkAAAAAAgAAAAEAAAADAAAAbv///wAAAAEQAAAA" +
    "EAAAAAMAAAAsAAAAWP///xwAAABzZXF1ZW50aWFsXzEvZGVuc2VfMS9CaWFzQWRk" +
    "AAAAAAEAAAADAAAAtv///wAAAAEQAAAAEAAAAAIAAAAoAAAAoP///xsAAABzZXF1" +
    "ZW50aWFsXzEvZGVuc2VfMS9NYXRNdWwAAgAAAAMAAAADAAAAAAAWABgAFAAAABAA" +
    "DAAIAAAAAAAAAAcAFgAAAAAAAAEUAAAAFAAAAAEAAAAYAAAABAAEAAQAAAAHAAAA" +
    "aW5wdXRfYwACAAAAAQAAAAMAAAABAAAAEAAAAAwADAALAAAAAAAEAAwAAAAJAAAA" +
    "AAAACQ=="


fun decodeBase64(base64: String): ByteArray {
    val table = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
    val clean = base64.filter { it in table || it == '=' }
    val data = clean.takeWhile { it != '=' }

    val output = mutableListOf<Byte>()
    var bitBuffer = 0
    var bitCount = 0

    for (char in data) {
        val value = table.indexOf(char)
        if (value == -1) continue
        bitBuffer = (bitBuffer shl 6) or value
        bitCount += 6
        if (bitCount >= 8) {
            bitCount -= 8
            output.add(((bitBuffer shr bitCount) and 0xFF).toByte())
        }
    }
    return output.toByteArray()
}
