// Auto-generated by GitHub Actions.
// This file is generated from LiteRT build_config.h.in for cinterop.

#ifndef LITERT_BUILD_COMMON_BUILD_CONFIG_H_
#define LITERT_BUILD_COMMON_BUILD_CONFIG_H_

// Default feature configuration.
#define LITERT_BUILD_CONFIG_DISABLE_GPU 0
#define LITERT_BUILD_CONFIG_DISABLE_NPU 0

#if LITERT_BUILD_CONFIG_DISABLE_GPU
#define LITERT_DISABLE_GPU
#endif

#if LITERT_BUILD_CONFIG_DISABLE_NPU
#define LITERT_DISABLE_NPU
#endif

#endif  // LITERT_BUILD_COMMON_BUILD_CONFIG_H_
