name: Build LiteRT Native Libraries

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  copy-headers:
    name: Copy LiteRT Headers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout LiteRT
        uses: actions/checkout@v4
        with:
          repository: google-ai-edge/LiteRT
          path: LiteRT-repo
          lfs: true
          sparse-checkout: |
            litert/c
            litert/build_common
          sparse-checkout-cone-mode: false

      - name: Copy headers
        run: |
          DEST_PATH="library/kmplitert-core/src/nativeInterop/include/litert/c"
          rm -rf "$DEST_PATH"
          mkdir -p "$(dirname "$DEST_PATH")"
          
          find LiteRT-repo/litert/c -type f -name "*.h" | while read -r file; do
            relative="${file#LiteRT-repo/litert/c/}"
            mkdir -p "$DEST_PATH/$(dirname "$relative")"
            cp "$file" "$DEST_PATH/$relative"
          done

      - name: Commit and push
        uses: ./.github/actions/commit-and-push
        with:
          message: "Update LiteRT headers"
          add: "library/kmplitert-core/src/nativeInterop/include/litert/c"

  copy-libraries:
    needs: copy-headers
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - platform: linux
            arch: x86_64
            src: linux_x86_64
            dest: linux/x86-64

          - platform: linux
            arch: arm64
            src: linux_arm64
            dest: linux/arm64

          - platform: macos
            arch: arm64
            src: macos_arm64
            dest: macos/arm64

          - platform: windows
            arch: x86_64
            src: windows_x86_64
            dest: windows/x86-64

          - platform: ios
            arch: arm64
            src: ios_arm64
            dest: ios/arm64

          - platform: ios
            arch: sim-arm64
            src: ios_sim_arm64
            dest: ios/sim-arm64

          - platform: android
            arch: arm32
            src: android_arm32
            dest: android/arm32

          - platform: android
            arch: arm64
            src: android_arm64
            dest: android/arm64

          - platform: android
            arch: x86-64
            src: android_x86_64
            dest: android/x86-64

    name: LiteRT (${{ matrix.platform }}-${{ matrix.arch }})
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout LiteRT
        uses: actions/checkout@v4
        with:
          repository: google-ai-edge/LiteRT
          path: LiteRT-repo
          lfs: true
          sparse-checkout: |
            litert/c
            litert/prebuilt
          sparse-checkout-cone-mode: false

      - name: Prepare Artifacts
        run: |
          DEST_PATH="library/kmplitert-core/src/nativeInterop/lib/litert/${{ matrix.dest }}"
          rm -rf "$DEST_PATH"
          mkdir -p "$DEST_PATH"
          
          echo "Copying libraries from ${{ matrix.src }}..."
          cp -vL LiteRT-repo/litert/prebuilt/${{ matrix.src }}/* "$DEST_PATH"
          rm -rf LiteRT-repo

      - name: Commit and push
        uses: ./.github/actions/commit-and-push
        with:
          message: "Update LiteRT prebuilt: ${{ matrix.platform }} ${{ matrix.arch }}"
          add: "library/kmplitert-core/src/nativeInterop/lib/litert/${{ matrix.dest }}"