name: Tool CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - 'tool/**'
      - 'gradle/**'
      - '*.gradle.kts'
      - 'gradle.properties'

jobs:
  linux-android-web:
    name: Linux, Android & Web (Tests Only)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle

      - name: Run Tests (Linux, Android, JS, Wasm)
        run: |
          chmod +x gradlew
          ./gradlew :tool:linuxX64Test \
                    :tool:linkDebugTestAndroidNativeArm64 \
                    :tool:linkDebugTestAndroidNativeX64 \
                    :tool:testAndroidHostTest \
                    :tool:jsBrowserTest \
                    :tool:wasmJsBrowserTest \
                    --stacktrace --info --no-daemon

  android-native:
    name: Android Native (Link Only)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle

      - name: Link Android Native Tests
        run: |
          chmod +x gradlew
          ./gradlew :tool:linkDebugTestAndroidNativeArm64 \
                    :tool:linkDebugTestAndroidNativeX64 \
                    --no-daemon

  macos-ios:
    name: MacOS & iOS (Tests Only)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle

      - name: Run Tests (MacOS, iOS)
        run: |
          chmod +x gradlew
          ./gradlew :tool:macosArm64Test \
                    :tool:iosSimulatorArm64Test \
                    --stacktrace --info --no-daemon

  windows:
    name: Windows (Tests Only)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle

      - name: Run Tests (Windows)
        shell: bash
        run: |
          ./gradlew :tool:mingwX64Test \
                    --stacktrace --info --no-daemon
