name: Publish

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  release:
    types:
      - released
      - prereleased

jobs:
  test-jvm:
    name: Test JVM & Android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run JVM & Android Tests
        run: ./gradlew jvmTest testDebugUnitTest --no-configuration-cache

  test-native:
    name: Native • ${{ matrix.name }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS
            os: macos-latest
            task: "macosArm64Test iosSimulatorArm64Test"

          - name: Linux
            os: ubuntu-latest
            task: linuxX64Test

          - name: Windows
            os: windows-latest
            task: mingwX64Test

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle

      - name: Make gradlew executable
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Run Native Tests
        shell: bash
        run: ./gradlew ${{ matrix.task }} --no-configuration-cache

  test-web:
    name: Test JS & Wasm
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run Web Tests
        run: ./gradlew jsBrowserTest wasmJsBrowserTest --no-configuration-cache

  publish:
    name: Publish to Maven Central

    if: github.event_name == 'release'

    needs:
      - test-jvm
      - test-native
      - test-web

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Publish
        run: ./gradlew publishToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}